export interface MacroTargetFormProps {
    mode: string,
    enableProtein: boolean,
    proteinTarget: number,
    proteinGrams?: number,
    enableCarbs: boolean,
    carbsTarget: number,
    carbGrams?: number,
    enableFat: boolean,
    fatTarget: number,
    fatGrams?: number,
    onEnableProteinChange: Function,
    onProteinChange: Function,
    onEnableCarbsChange: Function,
    onCarbsChange: Function,
    onEnableFatChange: Function,
    onFatChange: Function,
    error?: string,
}
