export interface DietSettingsUpdateRequest {
    manuallyCalculateCalories: boolean,
    macroTargetMode: number,
    dietMode: number,
    dietPercentage: number,
    enableCalorieTarget: boolean,
    calorieTarget: number,
    enableProteinTarget: boolean,
    proteinTarget: number,
    proteinPercentage: number,
    enableCarbohydratesTarget: boolean,
    carbohydratesTarget: number,
    carbohydratesPercentage: number,
    enableFatTarget: boolean,
    fatTarget: number,
    fatPercentage: number,
}
