export interface MacroTargetFormProps {
    mode: string,
    enableProtein: boolean,
    proteinTarget: number,
    proteinGrams?: number,
    enableCarbs: boolean,
    carbsTarget: number,
    carbGrams?: number,
    enableFat: boolean,
    fatTarget: number,
    fatGrams?: number,
    onEnableProteinChange: (e: React.ChangeEvent<HTMLInputElement>) => void,
    onProteinChange: (e: React.ChangeEvent<HTMLInputElement>) => void,
    onEnableCarbsChange: (e: React.ChangeEvent<HTMLInputElement>) => void,
    onCarbsChange: (e: React.ChangeEvent<HTMLInputElement>) => void,
    onEnableFatChange: (e: React.ChangeEvent<HTMLInputElement>) => void,
    onFatChange: (e: React.ChangeEvent<HTMLInputElement>) => void,
    error?: string,
}
